/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/


-- Find total customers by countries
SELECT country, COUNT(*) total_customer
FROM gold.dim_customers
GROUP BY country;


-- Find total customers by gender
SELECT gender, COUNT(*) total_customer
FROM gold.dim_customers
GROUP BY gender;


-- Find total products by category
SELECT category, subcategory, COUNT(*) total_products
FROM gold.dim_products
GROUP BY category, subcategory;


-- What is the average costs in each category
SELECT category, AVG(cost) average_cost
FROM gold.dim_products
GROUP BY category;



-- What is the total revenue generated for each category
SELECT *
FROM gold.dim_products

SELECT *
FROM gold.fact_sales

SELECT p.category, SUM(s.sales_amount) total_revenue
FROM gold.dim_products p
LEFT JOIN gold.fact_sales s
		ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


--  Find total revenue generated by each customer
SELECT c.customer_number, c.first_name, c.last_name, SUM(s.sales_amount) total_revenue
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
		ON c.customer_key = s.customer_key
GROUP BY c.customer_number, c.first_name, c.last_name
ORDER BY total_revenue DESC;


-- What is the distribution of sold items across countries
SELECT c.country, SUM(s.quantity) total_quantity
FROM gold.dim_customers c
LEFT JOIN gold.fact_sales s
		ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY total_quantity DESC;